---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-repo
    destinationPVC: data-dest
    copyMethod: None
    cacheCapacity: 1Gi
    restoreAsOf: 1980-08-10T23:59:59-04:00

