---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
delete:
- apiVersion: v1
  kind: Pod
  name: verify
- apiVersion: volsync.backube/v1alpha1
  kind: ReplicationDestination
  name: restore
- apiVersion: volsync.backube/v1alpha1
  kind: ReplicationSource
  name: data-source
- apiVersion: batch/v1
  kind: Job
  name: verify